name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write
  security-events: write
  actions: read

jobs:
  terraform:
    uses: mtopps/github-workflows/.github/workflows/tf-plan-gcp.yml@main
    secrets: inherit
    with:
      GCP_BUCKET_PREFIX: ${{ vars.GCP_BUCKET_PREFIX }}
      GCP_BUCKET: ${{ vars.GCP_BUCKET }}